"""Add image_url and plan_url to products table

Revision ID: 08063dc119e8
Revises: eb00eeab1144
Create Date: 2025-12-11 15:08:27.337950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08063dc119e8'
down_revision: Union[str, Sequence[str], None] = 'eb00eeab1144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Short code (e.g., NET30, COD, 50-50)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Payment condition name'),
    sa.Column('revision', sa.String(length=10), nullable=False, comment='Payment condition revision (A, B, C...)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description'),
    sa.Column('days_to_pay', sa.Integer(), nullable=True, comment='Number of days for payment (for NET terms)'),
    sa.Column('percentage_advance', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='Percentage required as advance payment'),
    sa.Column('percentage_on_delivery', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='Percentage due on delivery'),
    sa.Column('percentage_after_delivery', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='Percentage due after delivery'),
    sa.Column('days_after_delivery', sa.Integer(), nullable=True, comment='Days after delivery for final payment'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this is the default payment condition'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.CheckConstraint('(percentage_advance + percentage_on_delivery + percentage_after_delivery) = 100', name=op.f('ck_payment_conditions_ck_payment_condition_percentages_sum_100')),
    sa.CheckConstraint('percentage_advance >= 0 AND percentage_advance <= 100', name=op.f('ck_payment_conditions_ck_payment_condition_advance_valid')),
    sa.CheckConstraint('percentage_after_delivery >= 0 AND percentage_after_delivery <= 100', name=op.f('ck_payment_conditions_ck_payment_condition_after_delivery_valid')),
    sa.CheckConstraint('percentage_on_delivery >= 0 AND percentage_on_delivery <= 100', name=op.f('ck_payment_conditions_ck_payment_condition_on_delivery_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_conditions'))
    )
    op.create_index(op.f('ix_payment_conditions_code'), 'payment_conditions', ['code'], unique=True)
    op.create_index(op.f('ix_payment_conditions_is_active'), 'payment_conditions', ['is_active'], unique=False)
    op.create_table('transports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Transport company name'),
    sa.Column('delivery_number', sa.String(length=100), nullable=True, comment='Delivery tracking/reference number'),
    sa.Column('transport_type', sa.String(length=50), nullable=False, comment='Type (own, carrier, courier, freight_forwarder)'),
    sa.Column('contact_name', sa.String(length=200), nullable=True, comment='Contact person name'),
    sa.Column('contact_phone', sa.String(length=50), nullable=True, comment='Contact phone number'),
    sa.Column('contact_email', sa.String(length=100), nullable=True, comment='Contact email'),
    sa.Column('website', sa.String(length=200), nullable=True, comment='Company website'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.CheckConstraint("transport_type IN ('own', 'carrier', 'courier', 'freight_forwarder')", name=op.f('ck_transports_ck_transport_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transports'))
    )
    op.create_index(op.f('ix_transports_delivery_number'), 'transports', ['delivery_number'], unique=False)
    op.create_index(op.f('ix_transports_is_active'), 'transports', ['is_active'], unique=False)
    op.create_index(op.f('ix_transports_name'), 'transports', ['name'], unique=True)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=False, comment='Unique quote number (e.g., Q-2025-001)'),
    sa.Column('subject', sa.String(length=200), nullable=False, comment='Quote subject or description'),
    sa.Column('revision', sa.String(length=10), nullable=False, comment='Quote revision (A, B, C...)'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='Customer company'),
    sa.Column('contact_id', sa.Integer(), nullable=True, comment='Customer contact person'),
    sa.Column('branch_id', sa.Integer(), nullable=True, comment='Customer branch'),
    sa.Column('staff_id', sa.Integer(), nullable=False, comment='Sales person responsible'),
    sa.Column('status_id', sa.Integer(), nullable=False, comment='Quote status (draft, sent, accepted, rejected)'),
    sa.Column('quote_date', sa.Date(), nullable=False, comment='Quote creation date'),
    sa.Column('valid_until', sa.Date(), nullable=True, comment='Quote expiration date'),
    sa.Column('shipping_date', sa.Date(), nullable=True, comment='Estimated shipping date'),
    sa.Column('incoterm_id', sa.Integer(), nullable=True, comment='Shipping terms (EXW, FOB, CIF, etc.)'),
    sa.Column('currency_id', sa.Integer(), nullable=False, comment='Quote currency'),
    sa.Column('exchange_rate', sa.DECIMAL(precision=12, scale=6), nullable=True, comment='Exchange rate at time of quote'),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Sum of all line items before tax'),
    sa.Column('tax_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='Tax percentage (e.g., 19 for IVA in Chile)'),
    sa.Column('tax_amount', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Calculated tax amount'),
    sa.Column('total', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Total amount including tax'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Customer-visible notes'),
    sa.Column('internal_notes', sa.Text(), nullable=True, comment='Internal notes only'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_quotes_ck_quote_subtotal_positive')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_quotes_ck_quote_tax_positive')),
    sa.CheckConstraint('tax_percentage >= 0 AND tax_percentage <= 100', name=op.f('ck_quotes_ck_quote_tax_percentage_valid')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_quotes_ck_quote_total_positive')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_quotes_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_quotes_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_quotes_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('fk_quotes_currency_id_currencies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incoterm_id'], ['incoterms.id'], name=op.f('fk_quotes_incoterm_id_incoterms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_quotes_staff_id_staff'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['quote_statuses.id'], name=op.f('fk_quotes_status_id_quote_statuses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes'))
    )
    op.create_index('ix_quote_company_date', 'quotes', ['company_id', 'quote_date'], unique=False)
    op.create_index('ix_quote_status_date', 'quotes', ['status_id', 'quote_date'], unique=False)
    op.create_index(op.f('ix_quotes_company_id'), 'quotes', ['company_id'], unique=False)
    op.create_index(op.f('ix_quotes_contact_id'), 'quotes', ['contact_id'], unique=False)
    op.create_index(op.f('ix_quotes_is_active'), 'quotes', ['is_active'], unique=False)
    op.create_index(op.f('ix_quotes_quote_date'), 'quotes', ['quote_date'], unique=False)
    op.create_index(op.f('ix_quotes_quote_number'), 'quotes', ['quote_number'], unique=True)
    op.create_index(op.f('ix_quotes_staff_id'), 'quotes', ['staff_id'], unique=False)
    op.create_index(op.f('ix_quotes_status_id'), 'quotes', ['status_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False, comment='Unique order number (e.g., O-2025-001)'),
    sa.Column('revision', sa.String(length=10), nullable=False, comment='Order revision (A, B, C...)'),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment="Order type: 'sales' or 'purchase'"),
    sa.Column('quote_id', sa.Integer(), nullable=True, comment='Source quote if order created from accepted quote'),
    sa.Column('customer_quote_number', sa.String(length=100), nullable=True, comment="Customer's quote/reference number"),
    sa.Column('project_number', sa.String(length=100), nullable=True, comment='Project number/identifier'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='Customer or supplier company'),
    sa.Column('contact_id', sa.Integer(), nullable=True, comment='Contact person'),
    sa.Column('branch_id', sa.Integer(), nullable=True, comment='Company branch'),
    sa.Column('shipping_address_id', sa.Integer(), nullable=True, comment='Shipping/delivery address'),
    sa.Column('billing_address_id', sa.Integer(), nullable=True, comment='Billing/invoice address'),
    sa.Column('staff_id', sa.Integer(), nullable=False, comment='Staff member managing this order'),
    sa.Column('status_id', sa.Integer(), nullable=False, comment='Order status (pending, confirmed, processing, shipped, completed, cancelled)'),
    sa.Column('payment_status_id', sa.Integer(), nullable=False, comment='Payment status (unpaid, partial, paid, overdue)'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='Date order was placed'),
    sa.Column('required_date', sa.Date(), nullable=True, comment='Date customer requires delivery'),
    sa.Column('promised_date', sa.Date(), nullable=True, comment='Date we promised to deliver'),
    sa.Column('shipped_date', sa.Date(), nullable=True, comment='Actual shipping date'),
    sa.Column('completed_date', sa.Date(), nullable=True, comment='Date order was completed'),
    sa.Column('incoterm_id', sa.Integer(), nullable=True, comment='Shipping terms (EXW, FOB, CIF, etc.)'),
    sa.Column('currency_id', sa.Integer(), nullable=False, comment='Order currency'),
    sa.Column('exchange_rate', sa.DECIMAL(precision=12, scale=6), nullable=True, comment='Exchange rate at time of order'),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Total before tax'),
    sa.Column('tax_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='Tax percentage'),
    sa.Column('tax_amount', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Calculated tax amount'),
    sa.Column('shipping_cost', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Shipping/freight cost'),
    sa.Column('other_costs', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Other additional costs'),
    sa.Column('total', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Grand total'),
    sa.Column('payment_terms', sa.String(length=200), nullable=True, comment='Payment terms description'),
    sa.Column('is_export', sa.Boolean(), nullable=False, comment='Is export order'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Customer-visible notes'),
    sa.Column('internal_notes', sa.Text(), nullable=True, comment='Internal notes only'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.CheckConstraint("order_type IN ('sales', 'purchase')", name=op.f('ck_orders_ck_order_type_valid')),
    sa.CheckConstraint('other_costs >= 0', name=op.f('ck_orders_ck_order_other_costs_positive')),
    sa.CheckConstraint('shipping_cost >= 0', name=op.f('ck_orders_ck_order_shipping_positive')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_orders_ck_order_subtotal_positive')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_orders_ck_order_tax_positive')),
    sa.CheckConstraint('tax_percentage >= 0 AND tax_percentage <= 100', name=op.f('ck_orders_ck_order_tax_percentage_valid')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_orders_ck_order_total_positive')),
    sa.ForeignKeyConstraint(['billing_address_id'], ['addresses.id'], name=op.f('fk_orders_billing_address_id_addresses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_orders_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_orders_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_orders_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('fk_orders_currency_id_currencies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incoterm_id'], ['incoterms.id'], name=op.f('fk_orders_incoterm_id_incoterms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_status_id'], ['payment_statuses.id'], name=op.f('fk_orders_payment_status_id_payment_statuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_orders_quote_id_quotes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['addresses.id'], name=op.f('fk_orders_shipping_address_id_addresses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_orders_staff_id_staff'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['order_statuses.id'], name=op.f('fk_orders_status_id_order_statuses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index('ix_order_company_date', 'orders', ['company_id', 'order_date'], unique=False)
    op.create_index('ix_order_payment_status', 'orders', ['payment_status_id'], unique=False)
    op.create_index('ix_order_status_date', 'orders', ['status_id', 'order_date'], unique=False)
    op.create_index(op.f('ix_orders_billing_address_id'), 'orders', ['billing_address_id'], unique=False)
    op.create_index(op.f('ix_orders_company_id'), 'orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_orders_contact_id'), 'orders', ['contact_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_quote_number'), 'orders', ['customer_quote_number'], unique=False)
    op.create_index(op.f('ix_orders_is_active'), 'orders', ['is_active'], unique=False)
    op.create_index(op.f('ix_orders_is_export'), 'orders', ['is_export'], unique=False)
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_payment_status_id'), 'orders', ['payment_status_id'], unique=False)
    op.create_index(op.f('ix_orders_project_number'), 'orders', ['project_number'], unique=False)
    op.create_index(op.f('ix_orders_quote_id'), 'orders', ['quote_id'], unique=True)
    op.create_index(op.f('ix_orders_shipping_address_id'), 'orders', ['shipping_address_id'], unique=False)
    op.create_index(op.f('ix_orders_staff_id'), 'orders', ['staff_id'], unique=False)
    op.create_index(op.f('ix_orders_status_id'), 'orders', ['status_id'], unique=False)
    op.create_table('quote_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False, comment='Parent quote'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Product being quoted'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Display order of line items'),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=3), nullable=False, comment='Quantity being quoted'),
    sa.Column('unit_price', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Price per unit (snapshot at quote time)'),
    sa.Column('discount_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='Discount percentage for this line'),
    sa.Column('discount_amount', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Calculated discount amount'),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Line total (quantity * unit_price - discount)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Line item specific notes'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_quote_products_ck_quote_product_discount_positive')),
    sa.CheckConstraint('discount_percentage >= 0 AND discount_percentage <= 100', name=op.f('ck_quote_products_ck_quote_product_discount_percentage_valid')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_quote_products_ck_quote_product_quantity_positive')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_quote_products_ck_quote_product_subtotal_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_quote_products_ck_quote_product_price_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_quote_products_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_quote_products_quote_id_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_products'))
    )
    op.create_index('ix_quote_product_quote', 'quote_products', ['quote_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_quote_products_product_id'), 'quote_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_quote_products_quote_id'), 'quote_products', ['quote_id'], unique=False)
    op.create_table('delivery_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_number', sa.String(length=50), nullable=False, comment='Unique delivery order number (e.g., GD-2025-001)'),
    sa.Column('revision', sa.String(length=10), nullable=False, comment='Delivery order revision (A, B, C...)'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Source order'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='Customer company'),
    sa.Column('address_id', sa.Integer(), nullable=False, comment='Delivery address'),
    sa.Column('transport_id', sa.Integer(), nullable=True, comment='Transport/carrier information'),
    sa.Column('staff_id', sa.Integer(), nullable=False, comment='Staff member responsible'),
    sa.Column('delivery_date', sa.Date(), nullable=False, comment='Planned delivery date'),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True, comment='Actual delivery date'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Delivery status (pending, in_transit, delivered, cancelled)'),
    sa.Column('tracking_number', sa.String(length=100), nullable=True, comment='Carrier tracking number'),
    sa.Column('delivery_instructions', sa.Text(), nullable=True, comment='Special delivery instructions'),
    sa.Column('signature_name', sa.String(length=200), nullable=True, comment='Name of person who received delivery'),
    sa.Column('signature_id', sa.String(length=50), nullable=True, comment='ID of person who received delivery'),
    sa.Column('signature_datetime', sa.DateTime(timezone=True), nullable=True, comment='Date and time of receipt'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.CheckConstraint("status IN ('pending', 'in_transit', 'delivered', 'cancelled')", name=op.f('ck_delivery_orders_ck_delivery_order_status_valid')),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_delivery_orders_address_id_addresses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_delivery_orders_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_delivery_orders_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_delivery_orders_staff_id_staff'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], name=op.f('fk_delivery_orders_transport_id_transports'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_orders'))
    )
    op.create_index('ix_delivery_order_company_date', 'delivery_orders', ['company_id', 'delivery_date'], unique=False)
    op.create_index('ix_delivery_order_status_date', 'delivery_orders', ['status', 'delivery_date'], unique=False)
    op.create_index(op.f('ix_delivery_orders_company_id'), 'delivery_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_delivery_orders_delivery_date'), 'delivery_orders', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_delivery_orders_delivery_number'), 'delivery_orders', ['delivery_number'], unique=True)
    op.create_index(op.f('ix_delivery_orders_is_active'), 'delivery_orders', ['is_active'], unique=False)
    op.create_index(op.f('ix_delivery_orders_order_id'), 'delivery_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_delivery_orders_status'), 'delivery_orders', ['status'], unique=False)
    op.create_table('invoices_export',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False, comment='Export invoice number'),
    sa.Column('revision', sa.String(length=10), nullable=False, comment='Invoice revision (A, B, C...)'),
    sa.Column('invoice_type', sa.String(length=10), nullable=False, comment='SII export document type (110=Factura Export, 111=Nota Débito, 112=Nota Crédito)'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Source order'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='Foreign customer company'),
    sa.Column('branch_id', sa.Integer(), nullable=True, comment='Customer branch'),
    sa.Column('staff_id', sa.Integer(), nullable=False, comment='Staff member who created invoice'),
    sa.Column('payment_status_id', sa.Integer(), nullable=False, comment='Payment status'),
    sa.Column('invoice_date', sa.Date(), nullable=False, comment='Invoice issue date'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Payment due date'),
    sa.Column('paid_date', sa.Date(), nullable=True, comment='Date invoice was fully paid'),
    sa.Column('shipping_date', sa.Date(), nullable=True, comment='Date goods were shipped'),
    sa.Column('currency_id', sa.Integer(), nullable=False, comment='Invoice currency (usually USD, EUR)'),
    sa.Column('exchange_rate', sa.DECIMAL(precision=12, scale=6), nullable=False, comment='Exchange rate to CLP at invoice date'),
    sa.Column('incoterm_id', sa.Integer(), nullable=False, comment='International shipping terms (required for exports)'),
    sa.Column('country_id', sa.Integer(), nullable=False, comment='Destination country'),
    sa.Column('port_of_loading', sa.String(length=100), nullable=True, comment='Port where goods are loaded'),
    sa.Column('port_of_discharge', sa.String(length=100), nullable=True, comment='Destination port'),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Subtotal in foreign currency'),
    sa.Column('total', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Total in foreign currency (exports usually tax-exempt)'),
    sa.Column('total_clp', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Total converted to CLP'),
    sa.Column('freight_cost', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='International freight cost'),
    sa.Column('insurance_cost', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Insurance cost'),
    sa.Column('payment_terms', sa.String(length=200), nullable=True, comment='Payment terms description'),
    sa.Column('letter_of_credit', sa.String(length=100), nullable=True, comment='Letter of credit reference'),
    sa.Column('customs_declaration', sa.String(length=100), nullable=True, comment='Customs declaration number (DIN)'),
    sa.Column('bill_of_lading', sa.String(length=100), nullable=True, comment='Bill of lading number (B/L)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.CheckConstraint("invoice_type IN ('110', '111', '112')", name=op.f('ck_invoices_export_ck_invoice_export_type_valid')),
    sa.CheckConstraint('exchange_rate > 0', name=op.f('ck_invoices_export_ck_invoice_export_exchange_rate_positive')),
    sa.CheckConstraint('freight_cost >= 0', name=op.f('ck_invoices_export_ck_invoice_export_freight_positive')),
    sa.CheckConstraint('insurance_cost >= 0', name=op.f('ck_invoices_export_ck_invoice_export_insurance_positive')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_invoices_export_ck_invoice_export_subtotal_positive')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_invoices_export_ck_invoice_export_total_positive')),
    sa.CheckConstraint('total_clp >= 0', name=op.f('ck_invoices_export_ck_invoice_export_total_clp_positive')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_invoices_export_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_invoices_export_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_invoices_export_country_id_countries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('fk_invoices_export_currency_id_currencies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incoterm_id'], ['incoterms.id'], name=op.f('fk_invoices_export_incoterm_id_incoterms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_invoices_export_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_status_id'], ['payment_statuses.id'], name=op.f('fk_invoices_export_payment_status_id_payment_statuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_invoices_export_staff_id_staff'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices_export'))
    )
    op.create_index('ix_invoice_export_company_date', 'invoices_export', ['company_id', 'invoice_date'], unique=False)
    op.create_index('ix_invoice_export_country', 'invoices_export', ['country_id'], unique=False)
    op.create_index('ix_invoice_export_status_date', 'invoices_export', ['payment_status_id', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_export_company_id'), 'invoices_export', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_export_invoice_date'), 'invoices_export', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_export_invoice_number'), 'invoices_export', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_export_is_active'), 'invoices_export', ['is_active'], unique=False)
    op.create_index(op.f('ix_invoices_export_order_id'), 'invoices_export', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoices_export_payment_status_id'), 'invoices_export', ['payment_status_id'], unique=False)
    op.create_table('invoices_sii',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False, comment='SII invoice number (folio)'),
    sa.Column('revision', sa.String(length=10), nullable=False, comment='Invoice revision (A, B, C...)'),
    sa.Column('invoice_type', sa.String(length=10), nullable=False, comment='SII document type (33=Factura, 34=Exenta, 56=Nota Débito, 61=Nota Crédito)'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Source order'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='Customer company'),
    sa.Column('branch_id', sa.Integer(), nullable=True, comment='Customer branch'),
    sa.Column('staff_id', sa.Integer(), nullable=False, comment='Staff member who created invoice'),
    sa.Column('payment_status_id', sa.Integer(), nullable=False, comment='Payment status'),
    sa.Column('invoice_date', sa.Date(), nullable=False, comment='Invoice issue date'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Payment due date'),
    sa.Column('paid_date', sa.Date(), nullable=True, comment='Date invoice was fully paid'),
    sa.Column('currency_id', sa.Integer(), nullable=False, comment='Invoice currency (usually CLP)'),
    sa.Column('exchange_rate', sa.DECIMAL(precision=12, scale=6), nullable=True, comment='Exchange rate if not CLP'),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Taxable base amount'),
    sa.Column('tax_amount', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='IVA amount (usually 19%)'),
    sa.Column('total', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Total including tax'),
    sa.Column('net_amount', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Net amount'),
    sa.Column('exempt_amount', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Tax-exempt amount'),
    sa.Column('payment_terms', sa.String(length=200), nullable=True, comment='Payment terms description'),
    sa.Column('sii_status', sa.String(length=50), nullable=True, comment='SII system status (pending, accepted, rejected)'),
    sa.Column('sii_track_id', sa.String(length=100), nullable=True, comment='SII tracking ID'),
    sa.Column('sii_xml', sa.Text(), nullable=True, comment='XML sent to SII'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.CheckConstraint("invoice_type IN ('33', '34', '56', '61', '39', '41')", name=op.f('ck_invoices_sii_ck_invoice_sii_type_valid')),
    sa.CheckConstraint('exempt_amount >= 0', name=op.f('ck_invoices_sii_ck_invoice_sii_exempt_positive')),
    sa.CheckConstraint('net_amount >= 0', name=op.f('ck_invoices_sii_ck_invoice_sii_net_positive')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_invoices_sii_ck_invoice_sii_subtotal_positive')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_invoices_sii_ck_invoice_sii_tax_positive')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_invoices_sii_ck_invoice_sii_total_positive')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_invoices_sii_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_invoices_sii_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('fk_invoices_sii_currency_id_currencies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_invoices_sii_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_status_id'], ['payment_statuses.id'], name=op.f('fk_invoices_sii_payment_status_id_payment_statuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_invoices_sii_staff_id_staff'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices_sii'))
    )
    op.create_index('ix_invoice_sii_company_date', 'invoices_sii', ['company_id', 'invoice_date'], unique=False)
    op.create_index('ix_invoice_sii_sii_status', 'invoices_sii', ['sii_status'], unique=False)
    op.create_index('ix_invoice_sii_status_date', 'invoices_sii', ['payment_status_id', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_sii_company_id'), 'invoices_sii', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_sii_invoice_date'), 'invoices_sii', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_sii_invoice_number'), 'invoices_sii', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_sii_is_active'), 'invoices_sii', ['is_active'], unique=False)
    op.create_index(op.f('ix_invoices_sii_order_id'), 'invoices_sii', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoices_sii_payment_status_id'), 'invoices_sii', ['payment_status_id'], unique=False)
    op.create_index(op.f('ix_invoices_sii_sii_status'), 'invoices_sii', ['sii_status'], unique=False)
    op.create_table('delivery_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_order_id', sa.Integer(), nullable=False, comment='Parent delivery order'),
    sa.Column('planned_date', sa.Date(), nullable=False, comment='Planned delivery date'),
    sa.Column('actual_date', sa.Date(), nullable=True, comment='Actual delivery date'),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='Quantity delivered in this shipment'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status (pending, completed, cancelled)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes for this delivery'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.CheckConstraint("status IN ('pending', 'completed', 'cancelled')", name=op.f('ck_delivery_dates_ck_delivery_date_status_valid')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_delivery_dates_ck_delivery_date_quantity_positive')),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_orders.id'], name=op.f('fk_delivery_dates_delivery_order_id_delivery_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_dates'))
    )
    op.create_index('ix_delivery_date_order_date', 'delivery_dates', ['delivery_order_id', 'planned_date'], unique=False)
    op.create_index(op.f('ix_delivery_dates_delivery_order_id'), 'delivery_dates', ['delivery_order_id'], unique=False)
    op.create_index(op.f('ix_delivery_dates_planned_date'), 'delivery_dates', ['planned_date'], unique=False)
    op.drop_index(op.f('ix_contact_email'), table_name='contacts')
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True, comment='URL of the product image'))
    op.add_column('products', sa.Column('plan_url', sa.String(length=500), nullable=True, comment='URL of the product plan/blueprint'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'plan_url')
    op.drop_column('products', 'image_url')
    op.create_index(op.f('ix_contact_email'), 'contacts', ['email'], unique=False)
    op.drop_index(op.f('ix_delivery_dates_planned_date'), table_name='delivery_dates')
    op.drop_index(op.f('ix_delivery_dates_delivery_order_id'), table_name='delivery_dates')
    op.drop_index('ix_delivery_date_order_date', table_name='delivery_dates')
    op.drop_table('delivery_dates')
    op.drop_index(op.f('ix_invoices_sii_sii_status'), table_name='invoices_sii')
    op.drop_index(op.f('ix_invoices_sii_payment_status_id'), table_name='invoices_sii')
    op.drop_index(op.f('ix_invoices_sii_order_id'), table_name='invoices_sii')
    op.drop_index(op.f('ix_invoices_sii_is_active'), table_name='invoices_sii')
    op.drop_index(op.f('ix_invoices_sii_invoice_number'), table_name='invoices_sii')
    op.drop_index(op.f('ix_invoices_sii_invoice_date'), table_name='invoices_sii')
    op.drop_index(op.f('ix_invoices_sii_company_id'), table_name='invoices_sii')
    op.drop_index('ix_invoice_sii_status_date', table_name='invoices_sii')
    op.drop_index('ix_invoice_sii_sii_status', table_name='invoices_sii')
    op.drop_index('ix_invoice_sii_company_date', table_name='invoices_sii')
    op.drop_table('invoices_sii')
    op.drop_index(op.f('ix_invoices_export_payment_status_id'), table_name='invoices_export')
    op.drop_index(op.f('ix_invoices_export_order_id'), table_name='invoices_export')
    op.drop_index(op.f('ix_invoices_export_is_active'), table_name='invoices_export')
    op.drop_index(op.f('ix_invoices_export_invoice_number'), table_name='invoices_export')
    op.drop_index(op.f('ix_invoices_export_invoice_date'), table_name='invoices_export')
    op.drop_index(op.f('ix_invoices_export_company_id'), table_name='invoices_export')
    op.drop_index('ix_invoice_export_status_date', table_name='invoices_export')
    op.drop_index('ix_invoice_export_country', table_name='invoices_export')
    op.drop_index('ix_invoice_export_company_date', table_name='invoices_export')
    op.drop_table('invoices_export')
    op.drop_index(op.f('ix_delivery_orders_status'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_order_id'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_is_active'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_delivery_number'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_delivery_date'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_company_id'), table_name='delivery_orders')
    op.drop_index('ix_delivery_order_status_date', table_name='delivery_orders')
    op.drop_index('ix_delivery_order_company_date', table_name='delivery_orders')
    op.drop_table('delivery_orders')
    op.drop_index(op.f('ix_quote_products_quote_id'), table_name='quote_products')
    op.drop_index(op.f('ix_quote_products_product_id'), table_name='quote_products')
    op.drop_index('ix_quote_product_quote', table_name='quote_products')
    op.drop_table('quote_products')
    op.drop_index(op.f('ix_orders_status_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_staff_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_shipping_address_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_quote_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_project_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_is_export'), table_name='orders')
    op.drop_index(op.f('ix_orders_is_active'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_quote_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_contact_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_company_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_billing_address_id'), table_name='orders')
    op.drop_index('ix_order_status_date', table_name='orders')
    op.drop_index('ix_order_payment_status', table_name='orders')
    op.drop_index('ix_order_company_date', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_quotes_status_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_staff_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_number'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_date'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_is_active'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_contact_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_company_id'), table_name='quotes')
    op.drop_index('ix_quote_status_date', table_name='quotes')
    op.drop_index('ix_quote_company_date', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_transports_name'), table_name='transports')
    op.drop_index(op.f('ix_transports_is_active'), table_name='transports')
    op.drop_index(op.f('ix_transports_delivery_number'), table_name='transports')
    op.drop_table('transports')
    op.drop_index(op.f('ix_payment_conditions_is_active'), table_name='payment_conditions')
    op.drop_index(op.f('ix_payment_conditions_code'), table_name='payment_conditions')
    op.drop_table('payment_conditions')
    # ### end Alembic commands ###
