"""add payment type lookup and link to payment conditions

Revision ID: 0dd3f1c106bf
Revises: 69d4d9a050c0
Create Date: 2025-12-28 17:28:18.765735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd3f1c106bf'
down_revision: Union[str, Sequence[str], None] = '69d4d9a050c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Payment type code'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Display name'),
    sa.Column('days', sa.Integer(), nullable=False, comment='Number of days for this payment type'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.CheckConstraint('days >= 0', name='payment_type_days_non_negative'),
    sa.CheckConstraint('length(trim(code)) > 0', name='payment_type_code_not_empty'),
    sa.CheckConstraint('length(trim(name)) > 0', name='payment_type_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type_id', sa.Integer(), nullable=False, comment='Payment type (30, 60, 90 days, etc.)'))
        batch_op.create_index(batch_op.f('ix_payment_conditions_payment_type_id'), ['payment_type_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_payment_conditions_payment_type_id_payment_types'), 'payment_types', ['payment_type_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_conditions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payment_conditions_payment_type_id_payment_types'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_conditions_payment_type_id'))
        batch_op.drop_column('payment_type_id')

    op.drop_table('payment_types')
    # ### end Alembic commands ###
