"""rename payment condition code to payment_condition_number

Revision ID: 69d4d9a050c0
Revises: a2587c89b2ce
Create Date: 2025-12-28 17:04:46.398992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d4d9a050c0'
down_revision: Union[str, Sequence[str], None] = 'a2587c89b2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_conditions', sa.Column('payment_condition_number', sa.String(length=20), nullable=False, comment='Short number/code (e.g., 001, NET30, COD)'))
    op.drop_index(op.f('ix_payment_conditions_code'), table_name='payment_conditions')
    op.create_index(op.f('ix_payment_conditions_payment_condition_number'), 'payment_conditions', ['payment_condition_number'], unique=True)
    op.drop_column('payment_conditions', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_conditions', sa.Column('code', sa.VARCHAR(length=20), nullable=False))
    op.drop_index(op.f('ix_payment_conditions_payment_condition_number'), table_name='payment_conditions')
    op.create_index(op.f('ix_payment_conditions_code'), 'payment_conditions', ['code'], unique=1)
    op.drop_column('payment_conditions', 'payment_condition_number')
    # ### end Alembic commands ###
