"""add trigram to sequences

Revision ID: 735494c7fad2
Revises: a2ea0f1e2dc9
Create Date: 2025-12-29 18:43:27.116697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735494c7fad2'
down_revision: Union[str, Sequence[str], None] = 'a2ea0f1e2dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequences', sa.Column('trigram', sa.String(length=3), nullable=True))
    op.create_index(op.f('ix_sequences_trigram'), 'sequences', ['trigram'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequences_trigram'), table_name='sequences')
    op.drop_column('sequences', 'trigram')
    # ### end Alembic commands ###
