"""Add supplier_reference and customs_number to products table

Revision ID: 9d605f536188
Revises: 08063dc119e8
Create Date: 2025-12-11 15:24:54.341222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d605f536188'
down_revision: Union[str, Sequence[str], None] = '08063dc119e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('supplier_reference', sa.String(length=100), nullable=True, comment='Supplier reference code'))
    op.add_column('products', sa.Column('customs_number', sa.String(length=50), nullable=True, comment='Customs clearance number'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'customs_number')
    op.drop_column('products', 'supplier_reference')
    # ### end Alembic commands ###
