"""rename_branch_to_plant

Revision ID: a2587c89b2ce
Revises: 9d605f536188
Create Date: 2025-12-15 16:14:10.578482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2587c89b2ce'
down_revision: Union[str, Sequence[str], None] = '9d605f536188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Plant name'),
    sa.Column('address', sa.Text(), nullable=True, comment='Plant address (full text)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Plant phone number'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Plant contact email'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='Company this plant belongs to'),
    sa.Column('city_id', sa.Integer(), nullable=True, comment='City where plant is located'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_plants_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_plants_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants'))
    )
    op.create_index('ix_plant_company_active', 'plants', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_plants_city_id'), 'plants', ['city_id'], unique=False)
    op.create_index(op.f('ix_plants_company_id'), 'plants', ['company_id'], unique=False)
    op.create_index(op.f('ix_plants_is_active'), 'plants', ['is_active'], unique=False)
    op.drop_index(op.f('ix_branch_company_active'), table_name='branches')
    op.drop_index(op.f('ix_branches_city_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_is_active'), table_name='branches')
    op.drop_table('branches')
    
    with op.batch_alter_table('invoices_export', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=True, comment='Customer plant'))
        batch_op.drop_constraint('fk_invoices_export_branch_id_branches', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_invoices_export_plant_id_plants'), 'plants', ['plant_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('invoices_sii', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=True, comment='Customer plant'))
        batch_op.drop_constraint('fk_invoices_sii_branch_id_branches', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_invoices_sii_plant_id_plants'), 'plants', ['plant_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=True, comment='Company plant'))
        batch_op.drop_constraint('fk_orders_branch_id_branches', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orders_plant_id_plants'), 'plants', ['plant_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True, comment='Unit (Unidad)'))
        batch_op.add_column(sa.Column('company_rut_id', sa.Integer(), nullable=True, comment='Specific customer RUT for this quote'))
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=True, comment='Customer plant'))
        batch_op.create_index(batch_op.f('ix_quotes_company_rut_id'), ['company_rut_id'], unique=False)
        batch_op.drop_constraint('fk_quotes_branch_id_branches', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_quotes_plant_id_plants'), 'plants', ['plant_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_quotes_company_rut_id_company_ruts'), 'company_ruts', ['company_rut_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('branch_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_quotes_company_rut_id_company_ruts'), 'quotes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotes_plant_id_plants'), 'quotes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quotes_branch_id_branches'), 'quotes', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_quotes_company_rut_id'), table_name='quotes')
    op.drop_column('quotes', 'plant_id')
    op.drop_column('quotes', 'company_rut_id')
    op.drop_column('quotes', 'unit')
    op.add_column('orders', sa.Column('branch_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_orders_plant_id_plants'), 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_branch_id_branches'), 'orders', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.drop_column('orders', 'plant_id')
    op.add_column('invoices_sii', sa.Column('branch_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_invoices_sii_plant_id_plants'), 'invoices_sii', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_sii_branch_id_branches'), 'invoices_sii', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.drop_column('invoices_sii', 'plant_id')
    op.add_column('invoices_export', sa.Column('branch_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_invoices_export_plant_id_plants'), 'invoices_export', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_export_branch_id_branches'), 'invoices_export', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.drop_column('invoices_export', 'plant_id')
    op.create_table('branches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_branches_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branches_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_index(op.f('ix_branches_is_active'), 'branches', ['is_active'], unique=False)
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_index(op.f('ix_branches_city_id'), 'branches', ['city_id'], unique=False)
    op.create_index(op.f('ix_branch_company_active'), 'branches', ['company_id', 'is_active'], unique=False)
    op.drop_index(op.f('ix_plants_is_active'), table_name='plants')
    op.drop_index(op.f('ix_plants_company_id'), table_name='plants')
    op.drop_index(op.f('ix_plants_city_id'), table_name='plants')
    op.drop_index('ix_plant_company_active', table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
