"""add_company_rut_id_to_quotes_and_orders

Revision ID: c98ad17d30ad
Revises: 1782d0df07a8
Create Date: 2026-01-13 21:52:23.908566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98ad17d30ad'
down_revision: Union[str, Sequence[str], None] = '1782d0df07a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('orders', sa.Column('company_rut_id', sa.Integer(), nullable=True, comment='Specific customer RUT for this order'))
    # op.create_index(op.f('ix_orders_company_rut_id'), 'orders', ['company_rut_id'], unique=False)
    # op.create_foreign_key(op.f('fk_orders_company_rut_id_company_ruts'), 'orders', 'company_ruts', ['company_rut_id'], ['id'], ondelete='RESTRICT')
    # op.alter_column('sequences', 'prefix',
    #            existing_type=sa.VARCHAR(length=20),
    #            type_=sa.String(length=10),
    #            existing_nullable=True)
    # op.drop_constraint(op.f('uq_sequence_name_year_prefix'), 'sequences', type_='unique')
    # op.drop_index(op.f('ix_sequences_lookup'), table_name='sequences')
    # op.create_index('ix_sequences_lookup', 'sequences', ['name', 'year', 'prefix', 'trigram'], unique=False)
    # op.create_index(op.f('ix_sequences_prefix'), 'sequences', ['prefix'], unique=False)
    # op.create_unique_constraint('uq_sequence_name_year_prefix_trigram', 'sequences', ['name', 'year', 'prefix', 'trigram'])
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sequence_name_year_prefix_trigram', 'sequences', type_='unique')
    op.drop_index(op.f('ix_sequences_prefix'), table_name='sequences')
    op.drop_index('ix_sequences_lookup', table_name='sequences')
    op.create_index(op.f('ix_sequences_lookup'), 'sequences', ['name', 'year', 'prefix'], unique=False)
    op.create_unique_constraint(op.f('uq_sequence_name_year_prefix'), 'sequences', ['name', 'year', 'prefix'])
    op.alter_column('sequences', 'prefix',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_orders_company_rut_id_company_ruts'), 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_company_rut_id'), table_name='orders')
    op.drop_column('orders', 'company_rut_id')
    # ### end Alembic commands ###
