"""Initial migration - All tables with revision columns

Revision ID: eb00eeab1144
Revises: 
Create Date: 2025-10-28 18:45:04.997482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb00eeab1144'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Company type name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of this company type'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_company_types_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_types'))
    )
    op.create_index(op.f('ix_company_types_name'), 'company_types', ['name'], unique=True)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Country name'),
    sa.Column('iso_code_alpha2', sa.String(length=2), nullable=True, comment='ISO 3166-1 alpha-2 code (e.g., CL, FR, US)'),
    sa.Column('iso_code_alpha3', sa.String(length=3), nullable=True, comment='ISO 3166-1 alpha-3 code (e.g., CHL, FRA, USA)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.CheckConstraint('iso_code_alpha2 IS NULL OR length(iso_code_alpha2) = 2', name=op.f('ck_countries_alpha2_length')),
    sa.CheckConstraint('iso_code_alpha3 IS NULL OR length(iso_code_alpha3) = 3', name=op.f('ck_countries_alpha3_length')),
    sa.CheckConstraint('length(trim(name)) >= 2', name=op.f('ck_countries_name_min_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('iso_code_alpha2', name=op.f('uq_countries_iso_code_alpha2')),
    sa.UniqueConstraint('iso_code_alpha3', name=op.f('uq_countries_iso_code_alpha3'))
    )
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False, comment='ISO 4217 currency code (e.g., CLP, EUR, USD)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Full currency name'),
    sa.Column('symbol', sa.String(length=5), nullable=True, comment='Currency symbol (e.g., $, €, US$)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.CheckConstraint('length(code) = 3', name=op.f('ck_currencies_code_exact_length')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_currencies_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currencies'))
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    op.create_index(op.f('ix_currencies_is_active'), 'currencies', ['is_active'], unique=False)
    op.create_table('family_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Family type name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of this family type'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_family_types_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_types'))
    )
    op.create_index(op.f('ix_family_types_name'), 'family_types', ['name'], unique=True)
    op.create_table('incoterms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False, comment='Incoterm code (e.g., EXW, FOB, CIF)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Full name (e.g., Ex Works)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of responsibilities'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.CheckConstraint('length(code) = 3', name=op.f('ck_incoterms_code_exact_length')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_incoterms_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incoterms'))
    )
    op.create_index(op.f('ix_incoterms_code'), 'incoterms', ['code'], unique=True)
    op.create_index(op.f('ix_incoterms_is_active'), 'incoterms', ['is_active'], unique=False)
    op.create_table('matters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Material name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Material description and properties'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_matters_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matters'))
    )
    op.create_index(op.f('ix_matters_name'), 'matters', ['name'], unique=True)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Type of entity this note belongs to (company, product, quote, etc.)'),
    sa.Column('entity_id', sa.Integer(), nullable=False, comment='ID of the entity this note belongs to'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='Optional title for the note'),
    sa.Column('content', sa.Text(), nullable=False, comment='Note content/body'),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notepriority'), nullable=False, comment='Priority level: low, normal, high, urgent'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Optional category (Technical, Commercial, Administrative, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('ix_note_entity', 'notes', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_note_priority_type', 'notes', ['priority', 'entity_type'], unique=False)
    op.create_index(op.f('ix_notes_category'), 'notes', ['category'], unique=False)
    op.create_index(op.f('ix_notes_entity_id'), 'notes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notes_entity_type'), 'notes', ['entity_type'], unique=False)
    op.create_index(op.f('ix_notes_priority'), 'notes', ['priority'], unique=False)
    op.create_table('order_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Status code'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Status display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.CheckConstraint('length(trim(code)) > 0', name=op.f('ck_order_statuses_code_not_empty')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_order_statuses_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_statuses'))
    )
    op.create_index(op.f('ix_order_statuses_code'), 'order_statuses', ['code'], unique=True)
    op.create_table('payment_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Status code'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Status display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.CheckConstraint('length(trim(code)) > 0', name=op.f('ck_payment_statuses_code_not_empty')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_payment_statuses_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_statuses'))
    )
    op.create_index(op.f('ix_payment_statuses_code'), 'payment_statuses', ['code'], unique=True)
    op.create_table('quote_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Status code (e.g., draft, sent, accepted)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Status display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.CheckConstraint('length(trim(code)) > 0', name=op.f('ck_quote_statuses_code_not_empty')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_quote_statuses_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_statuses'))
    )
    op.create_index(op.f('ix_quote_statuses_code'), 'quote_statuses', ['code'], unique=True)
    op.create_table('sales_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Sales type name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of sales type'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_sales_types_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_types'))
    )
    op.create_index(op.f('ix_sales_types_name'), 'sales_types', ['name'], unique=True)
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Service/department name'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='Service description'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index(op.f('ix_services_is_active'), 'services', ['is_active'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique username for login'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Unique email address'),
    sa.Column('first_name', sa.String(length=50), nullable=False, comment='First name(s)'),
    sa.Column('last_name', sa.String(length=50), nullable=False, comment='Last name(s)'),
    sa.Column('trigram', sa.String(length=3), nullable=True, comment='Three-letter unique staff code (optional)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Contact phone number (E.164 format recommended)'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='Job position/title'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether user account is active'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Whether user has admin privileges'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff'))
    )
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    op.create_index(op.f('ix_staff_is_active'), 'staff', ['is_active'], unique=False)
    op.create_index(op.f('ix_staff_trigram'), 'staff', ['trigram'], unique=True)
    op.create_index(op.f('ix_staff_username'), 'staff', ['username'], unique=True)
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='Unit code (e.g., pcs, kg, m, l)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Full unit name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.CheckConstraint('length(trim(code)) > 0', name=op.f('ck_units_code_not_empty')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_units_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units'))
    )
    op.create_index(op.f('ix_units_code'), 'units', ['code'], unique=True)
    op.create_index(op.f('ix_units_is_active'), 'units', ['is_active'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='City name'),
    sa.Column('country_id', sa.Integer(), nullable=False, comment='Country this city belongs to'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.CheckConstraint('length(trim(name)) >= 2', name=op.f('ck_cities_name_min_length')),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_cities_country_id_countries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities'))
    )
    op.create_index(op.f('ix_cities_country_id'), 'cities', ['country_id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_index('uq_city_name_country', 'cities', ['name', 'country_id'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Company legal name'),
    sa.Column('trigram', sa.String(length=3), nullable=False, comment='Three-letter unique company code'),
    sa.Column('main_address', sa.Text(), nullable=True, comment='Primary business address (full text)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Main phone number (E.164 format recommended)'),
    sa.Column('website', sa.String(length=200), nullable=True, comment='Company website URL'),
    sa.Column('intracommunity_number', sa.String(length=50), nullable=True, comment='EU intracommunity VAT number'),
    sa.Column('company_type_id', sa.Integer(), nullable=False, comment='Type of company (client, supplier, etc.)'),
    sa.Column('country_id', sa.Integer(), nullable=True, comment='Country of company registration'),
    sa.Column('city_id', sa.Integer(), nullable=True, comment='City of main office'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_companies_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_type_id'], ['company_types.id'], name=op.f('fk_companies_company_type_id_company_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_companies_country_id_countries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_city_id'), 'companies', ['city_id'], unique=False)
    op.create_index(op.f('ix_companies_company_type_id'), 'companies', ['company_type_id'], unique=False)
    op.create_index(op.f('ix_companies_country_id'), 'companies', ['country_id'], unique=False)
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index('ix_companies_name_trgm', 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_trigram'), 'companies', ['trigram'], unique=True)
    op.create_index('ix_companies_type_country', 'companies', ['company_type_id', 'country_id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.Text(), nullable=False, comment='Full address text including street, number, and details'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City name'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='Postal or ZIP code'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='Country name'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this is the default address for the company'),
    sa.Column('address_type', sa.Enum('DELIVERY', 'BILLING', 'HEADQUARTERS', 'BRANCH', name='addresstype'), nullable=False, comment='Type: delivery, billing, headquarters, branch'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='Company owning this address'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.CheckConstraint('length(trim(address)) >= 5', name=op.f('ck_addresses_address_min_length')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_addresses_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index(op.f('ix_addresses_address_type'), 'addresses', ['address_type'], unique=False)
    op.create_index(op.f('ix_addresses_company_id'), 'addresses', ['company_id'], unique=False)
    op.create_index('ix_addresses_company_id_is_default', 'addresses', ['company_id', 'is_default'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Branch name'),
    sa.Column('address', sa.Text(), nullable=True, comment='Branch address (full text)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Branch phone number'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Branch contact email'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='Company this branch belongs to'),
    sa.Column('city_id', sa.Integer(), nullable=True, comment='City where branch is located'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_branches_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branches_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_index('ix_branch_company_active', 'branches', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_branches_city_id'), 'branches', ['city_id'], unique=False)
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_index(op.f('ix_branches_is_active'), 'branches', ['is_active'], unique=False)
    op.create_table('company_ruts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False, comment='Chilean RUT (format: 12345678-9)'),
    sa.Column('is_main', sa.Boolean(), nullable=False, comment='Whether this is the main RUT for the company'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='Company this RUT belongs to'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_ruts_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_ruts'))
    )
    op.create_index('ix_company_rut_company_main', 'company_ruts', ['company_id', 'is_main'], unique=False)
    op.create_index(op.f('ix_company_ruts_company_id'), 'company_ruts', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_ruts_rut'), 'company_ruts', ['rut'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False, comment='First name(s)'),
    sa.Column('last_name', sa.String(length=50), nullable=False, comment='Last name(s)'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Email address'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Phone number'),
    sa.Column('mobile', sa.String(length=20), nullable=True, comment='Mobile phone number'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='Job position/title'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='Company this contact belongs to'),
    sa.Column('service_id', sa.Integer(), nullable=True, comment='Service/department this contact belongs to'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_contacts_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_contacts_service_id_services'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index('ix_contact_company_active', 'contacts', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_contact_email', 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_is_active'), 'contacts', ['is_active'], unique=False)
    op.create_index(op.f('ix_contacts_service_id'), 'contacts', ['service_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_type', sa.Enum('ARTICLE', 'NOMENCLATURE', 'SERVICE', name='producttype'), nullable=False, comment='Product type: article, nomenclature, or service'),
    sa.Column('reference', sa.String(length=50), nullable=False, comment='Unique product reference code'),
    sa.Column('designation_fr', sa.String(length=200), nullable=True, comment='Product designation in French'),
    sa.Column('designation_es', sa.String(length=200), nullable=True, comment='Product designation in Spanish'),
    sa.Column('designation_en', sa.String(length=200), nullable=True, comment='Product designation in English'),
    sa.Column('short_designation', sa.String(length=100), nullable=True, comment='Short/abbreviated designation'),
    sa.Column('revision', sa.String(length=20), nullable=True, comment='Product revision/version identifier'),
    sa.Column('family_type_id', sa.Integer(), nullable=True, comment='Product family classification'),
    sa.Column('matter_id', sa.Integer(), nullable=True, comment='Material/matter type'),
    sa.Column('sales_type_id', sa.Integer(), nullable=True, comment='Sales type classification'),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='Manufacturer/supplier company'),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='Purchase price from supplier'),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='Internal cost price'),
    sa.Column('sale_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='Sale price (base currency)'),
    sa.Column('sale_price_eur', sa.Numeric(precision=15, scale=2), nullable=True, comment='Sale price in EUR'),
    sa.Column('price_calculation_mode', sa.Enum('MANUAL', 'FROM_COMPONENTS', 'FROM_COST_MARGIN', name='pricecalculationmode'), nullable=False, comment='How price is calculated: manual, from_components, from_cost_margin'),
    sa.Column('margin_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Expected profit margin percentage'),
    sa.Column('stock_quantity', sa.Numeric(precision=15, scale=3), nullable=True, comment='Current stock quantity (null for SERVICE)'),
    sa.Column('minimum_stock', sa.Numeric(precision=15, scale=3), nullable=True, comment='Minimum stock threshold for alerts'),
    sa.Column('stock_location', sa.String(length=100), nullable=True, comment='Physical location in warehouse'),
    sa.Column('net_weight', sa.Numeric(precision=10, scale=3), nullable=True, comment='Net weight in kg'),
    sa.Column('gross_weight', sa.Numeric(precision=10, scale=3), nullable=True, comment='Gross weight in kg (with packaging)'),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True, comment='Length in mm'),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True, comment='Width in mm'),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True, comment='Height in mm'),
    sa.Column('volume', sa.Numeric(precision=10, scale=4), nullable=True, comment='Volume in cubic meters'),
    sa.Column('hs_code', sa.String(length=20), nullable=True, comment='Harmonized System code for customs'),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True, comment='Country where product is manufactured'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes and observations'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag (True=active, False=inactive)'),
    sa.CheckConstraint('cost_price IS NULL OR cost_price >= 0', name=op.f('ck_products_cost_price_non_negative')),
    sa.CheckConstraint('gross_weight IS NULL OR gross_weight >= 0', name=op.f('ck_products_gross_weight_non_negative')),
    sa.CheckConstraint('length(trim(reference)) >= 2', name=op.f('ck_products_reference_min_length')),
    sa.CheckConstraint('margin_percentage IS NULL OR (margin_percentage >= -100 AND margin_percentage <= 1000)', name=op.f('ck_products_margin_percentage_range')),
    sa.CheckConstraint('net_weight IS NULL OR net_weight >= 0', name=op.f('ck_products_net_weight_non_negative')),
    sa.CheckConstraint('purchase_price IS NULL OR purchase_price >= 0', name=op.f('ck_products_purchase_price_non_negative')),
    sa.CheckConstraint('sale_price IS NULL OR sale_price >= 0', name=op.f('ck_products_sale_price_non_negative')),
    sa.CheckConstraint('stock_quantity IS NULL OR stock_quantity >= 0', name=op.f('ck_products_stock_quantity_non_negative')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_products_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_type_id'], ['family_types.id'], name=op.f('fk_products_family_type_id_family_types'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_products_matter_id_matters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_type_id'], ['sales_types.id'], name=op.f('fk_products_sales_type_id_sales_types'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index('ix_products_family_type_id', 'products', ['family_type_id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_matter_id'), 'products', ['matter_id'], unique=False)
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    op.create_index('ix_products_product_type_active', 'products', ['product_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_reference'), 'products', ['reference'], unique=True)
    op.create_index(op.f('ix_products_sales_type_id'), 'products', ['sales_type_id'], unique=False)
    op.create_table('product_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='Parent product (NOMENCLATURE) containing this component'),
    sa.Column('component_id', sa.Integer(), nullable=False, comment='Component product (any type)'),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False, comment='Quantity of component required'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes about this component usage'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.CheckConstraint('parent_id != component_id', name=op.f('ck_product_components_no_self_reference')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_product_components_quantity_positive')),
    sa.ForeignKeyConstraint(['component_id'], ['products.id'], name=op.f('fk_product_components_component_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['products.id'], name=op.f('fk_product_components_parent_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_components')),
    sa.UniqueConstraint('parent_id', 'component_id', name='uq_parent_component')
    )
    op.create_index('ix_product_components_component_id', 'product_components', ['component_id'], unique=False)
    op.create_index('ix_product_components_parent_id', 'product_components', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_components_parent_id', table_name='product_components')
    op.drop_index('ix_product_components_component_id', table_name='product_components')
    op.drop_table('product_components')
    op.drop_index(op.f('ix_products_sales_type_id'), table_name='products')
    op.drop_index(op.f('ix_products_reference'), table_name='products')
    op.drop_index('ix_products_product_type_active', table_name='products')
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_index(op.f('ix_products_matter_id'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index('ix_products_family_type_id', table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_contacts_service_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_active'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_index('ix_contact_email', table_name='contacts')
    op.drop_index('ix_contact_company_active', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_company_ruts_rut'), table_name='company_ruts')
    op.drop_index(op.f('ix_company_ruts_company_id'), table_name='company_ruts')
    op.drop_index('ix_company_rut_company_main', table_name='company_ruts')
    op.drop_table('company_ruts')
    op.drop_index(op.f('ix_branches_is_active'), table_name='branches')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_city_id'), table_name='branches')
    op.drop_index('ix_branch_company_active', table_name='branches')
    op.drop_table('branches')
    op.drop_index('ix_addresses_company_id_is_default', table_name='addresses')
    op.drop_index(op.f('ix_addresses_company_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_address_type'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index('ix_companies_type_country', table_name='companies')
    op.drop_index(op.f('ix_companies_trigram'), table_name='companies')
    op.drop_index('ix_companies_name_trgm', table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_index(op.f('ix_companies_country_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_type_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_city_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index('uq_city_name_country', table_name='cities')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_country_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_units_is_active'), table_name='units')
    op.drop_index(op.f('ix_units_code'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_staff_username'), table_name='staff')
    op.drop_index(op.f('ix_staff_trigram'), table_name='staff')
    op.drop_index(op.f('ix_staff_is_active'), table_name='staff')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_is_active'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_sales_types_name'), table_name='sales_types')
    op.drop_table('sales_types')
    op.drop_index(op.f('ix_quote_statuses_code'), table_name='quote_statuses')
    op.drop_table('quote_statuses')
    op.drop_index(op.f('ix_payment_statuses_code'), table_name='payment_statuses')
    op.drop_table('payment_statuses')
    op.drop_index(op.f('ix_order_statuses_code'), table_name='order_statuses')
    op.drop_table('order_statuses')
    op.drop_index(op.f('ix_notes_priority'), table_name='notes')
    op.drop_index(op.f('ix_notes_entity_type'), table_name='notes')
    op.drop_index(op.f('ix_notes_entity_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_category'), table_name='notes')
    op.drop_index('ix_note_priority_type', table_name='notes')
    op.drop_index('ix_note_entity', table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_matters_name'), table_name='matters')
    op.drop_table('matters')
    op.drop_index(op.f('ix_incoterms_is_active'), table_name='incoterms')
    op.drop_index(op.f('ix_incoterms_code'), table_name='incoterms')
    op.drop_table('incoterms')
    op.drop_index(op.f('ix_family_types_name'), table_name='family_types')
    op.drop_table('family_types')
    op.drop_index(op.f('ix_currencies_is_active'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_company_types_name'), table_name='company_types')
    op.drop_table('company_types')
    # ### end Alembic commands ###
