"""
Constantes de negocio para la aplicación AK Group.

Este módulo re-exporta las constantes compartidas desde src.shared.constants
para mantener compatibilidad con código existente del backend.

Para nuevos desarrollos, importa directamente desde src.shared.constants
"""

# Re-exportar todas las constantes desde shared
from src.shared.constants import (
    # Monedas
    DEFAULT_CURRENCY,
    SUPPORTED_CURRENCIES,
    DEFAULT_TAX_RATE,
    # Paginación
    DEFAULT_PAGINATION_LIMIT,
    MAX_PAGINATION_LIMIT,
    # Estados
    QUOTE_STATUS_DRAFT,
    QUOTE_STATUS_SENT,
    QUOTE_STATUS_ACCEPTED,
    QUOTE_STATUS_REJECTED,
    QUOTE_STATUS_EXPIRED,
    ORDER_STATUS_PENDING,
    ORDER_STATUS_CONFIRMED,
    ORDER_STATUS_IN_PRODUCTION,
    ORDER_STATUS_READY,
    ORDER_STATUS_SHIPPED,
    ORDER_STATUS_DELIVERED,
    ORDER_STATUS_CANCELLED,
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_PARTIAL,
    PAYMENT_STATUS_PAID,
    PAYMENT_STATUS_OVERDUE,
    DELIVERY_STATUS_PENDING,
    DELIVERY_STATUS_IN_TRANSIT,
    DELIVERY_STATUS_DELIVERED,
    DELIVERY_STATUS_CANCELLED,
    # Tipos
    COMPANY_TYPE_CUSTOMER,
    COMPANY_TYPE_SUPPLIER,
    COMPANY_TYPE_BOTH,
    PRODUCT_TYPE_ARTICLE,
    PRODUCT_TYPE_NOMENCLATURE,
    PRODUCT_TYPE_SERVICE,
    ADDRESS_TYPE_DELIVERY,
    ADDRESS_TYPE_BILLING,
    ADDRESS_TYPE_HEADQUARTERS,
    ADDRESS_TYPE_BRANCH,
    TRANSPORT_TYPE_OWN,
    TRANSPORT_TYPE_CARRIER,
    TRANSPORT_TYPE_COURIER,
    TRANSPORT_TYPE_FREIGHT_FORWARDER,
    # Límites
    MIN_PASSWORD_LENGTH,
    MAX_DISCOUNT_PERCENTAGE,
    MIN_PRODUCT_QUANTITY,
    MAX_PRODUCT_QUANTITY,
    # Formatos
    DATE_FORMAT,
    DATETIME_FORMAT,
    RUT_REGEX,
    PHONE_REGEX,
    EMAIL_REGEX,
)

__all__ = [
    # Monedas
    "DEFAULT_CURRENCY",
    "SUPPORTED_CURRENCIES",
    "DEFAULT_TAX_RATE",
    # Paginación
    "DEFAULT_PAGINATION_LIMIT",
    "MAX_PAGINATION_LIMIT",
    # Estados de cotización
    "QUOTE_STATUS_DRAFT",
    "QUOTE_STATUS_SENT",
    "QUOTE_STATUS_ACCEPTED",
    "QUOTE_STATUS_REJECTED",
    "QUOTE_STATUS_EXPIRED",
    # Estados de orden
    "ORDER_STATUS_PENDING",
    "ORDER_STATUS_CONFIRMED",
    "ORDER_STATUS_IN_PRODUCTION",
    "ORDER_STATUS_READY",
    "ORDER_STATUS_SHIPPED",
    "ORDER_STATUS_DELIVERED",
    "ORDER_STATUS_CANCELLED",
    # Estados de pago
    "PAYMENT_STATUS_PENDING",
    "PAYMENT_STATUS_PARTIAL",
    "PAYMENT_STATUS_PAID",
    "PAYMENT_STATUS_OVERDUE",
    # Estados de entrega
    "DELIVERY_STATUS_PENDING",
    "DELIVERY_STATUS_IN_TRANSIT",
    "DELIVERY_STATUS_DELIVERED",
    "DELIVERY_STATUS_CANCELLED",
    # Tipos de empresa
    "COMPANY_TYPE_CUSTOMER",
    "COMPANY_TYPE_SUPPLIER",
    "COMPANY_TYPE_BOTH",
    # Tipos de producto
    "PRODUCT_TYPE_ARTICLE",
    "PRODUCT_TYPE_NOMENCLATURE",
    "PRODUCT_TYPE_SERVICE",
    # Tipos de dirección
    "ADDRESS_TYPE_DELIVERY",
    "ADDRESS_TYPE_BILLING",
    "ADDRESS_TYPE_HEADQUARTERS",
    "ADDRESS_TYPE_BRANCH",
    # Tipos de transporte
    "TRANSPORT_TYPE_OWN",
    "TRANSPORT_TYPE_CARRIER",
    "TRANSPORT_TYPE_COURIER",
    "TRANSPORT_TYPE_FREIGHT_FORWARDER",
    # Límites y validaciones
    "MIN_PASSWORD_LENGTH",
    "MAX_DISCOUNT_PERCENTAGE",
    "MIN_PRODUCT_QUANTITY",
    "MAX_PRODUCT_QUANTITY",
    # Formatos
    "DATE_FORMAT",
    "DATETIME_FORMAT",
    "RUT_REGEX",
    "PHONE_REGEX",
    "EMAIL_REGEX",
]
